name: Waka Readme

on: 
  workflow_dispatch:
  schedule:
    # Runs 00:00 UTC everyday
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: dexterpuru
          SHOW_LINES_OF_CODE : True
          SHOW_PROFILE_VIEWS : False
          SHOW_OS: False
          SHOW_PROJECTS : False
          SHOW_EDITORS : False
          SHOW_TIMEZONE: False
          SHOW_LANGUAGE_PER_REPO : False
          SHOW_LOC_CHART : False
